apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limit-global
  namespace: "{{NAMESPACE_APPS}}"
config:
  minute: 100
  limit_by: ip
  policy: local
plugin: rate-limiting
