apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 4
  template:
    spec:
      containers:
      - name: app2
        image: "{{REGISTRY_URL}}/app2:{{TAG_DA_IMAGEM_production}}"
