apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets
  namespace: "{{NAMESPACE_APPS}}"
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: app-secrets-k8s
  data:
  - secretKey: db-password
    remoteRef:
      key: "{{CAMINHO_DO_SECRET_NO_CLOUD}}"
